togglebyfeature:
  name: TEST
  featureStateMap:
    FEATURE1:
      enabled: true
      activationStrategy: RatioStrategy
      parameters:
        ratio: 50


toggly:
  SampleFeature:
    enabled: true
    activationStrategy: RatioStrategy
    parameters:
      ratio: 50